#!/bin/bash

# Script de creación automática de contenedores

echo "Antes de ejecutar este script asegúrate de que Docker está corriendo."
read -p "Pulsa Ctrl+C para cancelar o cualquier otra telca para continuar"

clear
# Eliminación de contenedores
echo "---------------------------"
echo "| ELIMINANDO CONTENEDORES |"
echo "---------------------------"
docker container stop scs-postfix-cont
docker container stop scs-apache-cont
docker container stop scs-mysql-cont
docker container stop scs-bind9-cont

docker container rm scs-postfix-cont
docker container rm scs-apache-cont
docker container rm scs-mysql-cont
docker container rm scs-bind9-cont

clear
# Eliminación de imágenes
echo "-----------------------"
echo "| ELIMINANDO IMÁGENES |"
echo "-----------------------"
docker image rm scs-postfix-img
docker image rm scs-apache-img
docker image rm scs-mysql-img
docker image rm scs-bind9-img

clear
# Eliminación de la red virtual
echo "--------------------------"
echo "| ELIMINANDO RED VIRTUAL |"
echo "--------------------------"
docker network prune

# Eliminación de volúmenes lógicos
echo "------------------------"
echo "| ELIMINANDO VOLÚMENES |"
echo "------------------------"
docker volume prune

clear
# Creación de imágenes
echo "--------------------"
echo "| CREANDO IMÁGENES |"
echo "--------------------"
cd ../images/scs-bind9-img/
docker build . -t scs-bind9-img -f scs-bind9-img.dockerfile
cd ../scs-mysql-img/
docker build . -t scs-mysql-img -f scs-mysql-img.dockerfile
cd ../scs-apache-img/
docker build . -t scs-apache-img -f scs-apache-img.dockerfile
cd ../scs-postfix-img/
docker build . -t scs-postfix-img -f scs-postfix-img.dockerfile

clear
# Creación de contenedores
echo "------------------------"
echo "| CREANDO CONTENEDORES |"
echo "------------------------"
cd ../../containers/
docker compose up -d
echo
echo "Fin de la instalación."
