#!/bin/bash

# Script de apagado de contenedores

echo "Antes de ejecutar este script asegúrate de que Docker está corriendo."
read -p "Pulsa Ctrl+C para cancelar o cualquier otra telca para continuar"

clear
# Parada de contenedores
echo "------------------------"
echo "| PARANDO CONTENEDORES |"
echo "------------------------"
docker container stop scs-postfix-cont
docker container stop scs-apache-cont
docker container stop scs-mysql-cont
docker container stop scs-bind9-cont